{"version": 2, "width": 120, "height": 30, "timestamp": 1731923718, "env": {"SHELL": "/bin/bash", "TERM": "xterm-256color"}}
[0.036762, "o", "\u001b[?2004h\u001b]0;diana_zh@DESKTOP-SDQ4U1P: ~/frontend-project-46\u0007\u001b[01;32mdiana_zh@DESKTOP-SDQ4U1P\u001b[00m:\u001b[01;34m~/frontend-project-46\u001b[00m$ "]
[0.944126, "o", "gendiff /home/di"]
[0.944628, "o", "ana_zh/frontend"]
[0.944935, "o", "-project-46/__"]
[0.945332, "o", "tests__"]
[0.945733, "o", "/__fixtures__/file1.yml /home/diana"]
[0.945975, "o", "_zh/fro"]
[0.946289, "o", "ntend-project-46"]
[0.946436, "o", "/__tes"]
[0.946591, "o", "ts__/__fixtu"]
[0.946877, "o", "res__/file2.yml"]
[2.205791, "o", "\r\n\u001b[?2004l\r"]
[2.306274, "o", "    common: {\r\n      + follow: false\r\n        setting1: Value 1\r\n      - setting2: 200\r\n      - setting3: true\r\n      + setting3: null\r\n      + setting4: blah blah\r\n      + setting5: {\r\n            key5: value5\r\n        }\r\n        setting6: {\r\n            doge: {\r\n              - wow: \r\n              + wow: so much\r\n            }\r\n            key: value\r\n          + ops: vops\r\n        }\r\n    }\r\n    group1: {\r\n      - baz: bas\r\n      + baz: bars\r\n        foo: bar\r\n      - nest: {\r\n            key: value\r\n        }\r\n      + nest: str\r\n    }\r\n  - group2: {\r\n        abc: 12345\r\n        deep: {\r\n            id: 45\r\n        }\r\n    }\r\n  + group3: {\r\n        deep: {\r\n            id: {\r\n                number: 45\r\n            }\r\n        }\r\n        fee: 100500\r\n    }\r\n"]
[2.309657, "o", "\u001b[?2004h\u001b]0;diana_zh@DESKTOP-SDQ4U1P: ~/frontend-project-46\u0007\u001b[01;32mdiana_zh@DESKTOP-SDQ4U1P\u001b[00m:\u001b[01;34m~/frontend-project-46\u001b[00m$ "]
[6.144672, "o", "e"]
[6.488666, "o", "x"]
[6.592602, "o", "i"]
[6.797891, "o", "t"]
[7.118145, "o", "\r\n\u001b[?2004l\rexit\r\n"]
