name: Node.js CI

on:
  push:
    push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
          with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
  
      - name: Run ESLint
        run: make lint
  
      - name: Run tests
        run: make test
      - name: Run Code Climate Coverage Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Run tests with coverage
        run: npm test -- --coverage
      - name: Upload coverage to Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: ./cc-test-reporter after-build --exit-code $?
      # - name: Test & publish code coverage
      #   # Publish code coverage on Code Climate
      #   # https://github.com/paambaati/codeclimate-action
      #   uses: paambaati/codeclimate-action@v5.0.0
      #   # Add Code Climate secret key
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #   with:
      #     coverageCommand: make test-coverage
      #     debug: true

